### ISSUE TITLE
Can you submit a complete setup guide?

### ISSUE THREAD

**Issue by hungthinhcntt** [gitbitex/gitbitex-web#1]
I find your source code very good, but I need a complete guide.
Functions:
Add coins
The support coins
Fiat currency?
...
I really thank you for sharing those issues.

**Comment by greensheng** [comment]
## INSTALL
*  Create mysql database, and make sure **binlog(ROW format)** enabled
* Run ddl.sql
* Install Redis
* Install Kafka
* Run: go build
* Edit conf.json,
* Run: ./gitbitex-sopt
* Done

**Comment by hungthinhcntt** [comment]
Thank you for reply
